### ISSUE TITLE
Not authorizing

### ISSUE THREAD

**Issue by singlekeycap** [tgraupmann/ChromaDiscordApp#8]
When the checkmark is checked, it doesn't pull up the authorization screen. The keyboard will animate with the authorized animation then go to waiting for authorization animation. Tried reinstalling Discord and Chroma Discord App but it didn't fix the issue

**Comment by Smexhy** [comment]
Exactly the same issue

**Comment by tgraupmann** [comment]
Thanks for the heads up! I just posted an update. I removed some unused legacy code and it should be fixed now. Let me know if that works for you. Thanks!

**Comment by singlekeycap** [comment]
Do you also know what's up with the Chroma SDK being really buggy and flashing LED's randomly as soon as any SDK app is turned on?

**Comment by Glenalth** [comment]
Same issue here. No authorization window so it just sits at waiting for authorization.

**Comment by RjGunner111** [comment]
still doesn't ask for verification, what's going on? @tgraupmann

**Comment by RjGunner111** [comment]
> still doesn't ask for verification, what's going on? @tgraupmann

nevermind, it now did, now i have a whole other issue, it's not displaying any chroma from the chroma discord app

**Comment by RjGunner111** [comment]
nevermind, i (think) it fully works now, but there is a slight bug about razer mamba elite with your software, idk if it's a big deal or not, if you want me to tell you it, lemme know, i don't mean to sound bossy or anything, just bare in mind
